/**
 * Prepares the static brand assets in /public from the two source logos.
 *
 *   npm run assets:prepare
 *
 * What it does
 *   1. Trims the transparent margin off dentista-logo.png so the mark fills
 *      its lavender tile (public/dentista-logo-trim.png).
 *   2. Renders favicon.png (64×64) and apple-icon.png (180×180) from logo.png.
 *
 * Re-runnable: every output is overwritten from the sources.
 * The SVG artwork (automation thumbnails and page backgrounds) is generated by
 * a separate script: node tools/generate-art.mjs
 */

import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, "public");

const SOURCES = {
  flux: path.join(PUBLIC_DIR, "logo.png"),
  dentista: path.join(PUBLIC_DIR, "dentista-logo.png"),
};

const OUTPUTS = {
  dentistaTrim: path.join(PUBLIC_DIR, "dentista-logo-trim.png"),
  favicon: path.join(PUBLIC_DIR, "favicon.png"),
  appleIcon: path.join(PUBLIC_DIR, "apple-icon.png"),
};

async function ensurePublicDir() {
  if (!existsSync(PUBLIC_DIR)) {
    await mkdir(PUBLIC_DIR, { recursive: true });
  }
}

function requireSource(file, label) {
  if (!existsSync(file)) {
    console.error(`✖ Missing ${label}: ${path.relative(ROOT, file)}`);
    process.exit(1);
  }
}

async function trimDentista() {
  const output = await sharp(SOURCES.dentista)
    .trim({ threshold: 1 })
    .png()
    .toBuffer({ resolveWithObject: true });

  await sharp(output.data).toFile(OUTPUTS.dentistaTrim);

  console.log(
    `  dentista-logo-trim.png  ${output.info.width}×${output.info.height}`,
  );
}

async function buildIcons() {
  await sharp(SOURCES.flux)
    .resize(64, 64, {
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toFile(OUTPUTS.favicon);
  console.log("  favicon.png             64×64");

  await sharp(SOURCES.flux)
    .resize(180, 180, {
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toFile(OUTPUTS.appleIcon);
  console.log("  apple-icon.png          180×180");
}

async function main() {
  console.log("\nPreparing brand assets…\n");

  await ensurePublicDir();
  requireSource(SOURCES.flux, "FLUXMEDIA logo");
  requireSource(SOURCES.dentista, "DENTISTA logo");

  await trimDentista();
  await buildIcons();

  console.log("\n✔ Assets ready in /public\n");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
